src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//AUTH
Auth::routes(['register' => false]);
Route::get('/profile', 'Profile\ProfileController@profile')->name('profile');
Route::get('/password', 'Profile\ProfileController@password')->name('password');
Route::get('/passport', 'PassportController@passport')->name('passport');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');


Route::post('/search', 'API\RequestsController@index')->name('search');

//Secretarias & Endpoints
Route::resource('/secretarias', 'SecretariaController');
Route::resource('/endpoints', 'API\EndpointsController');

//Roles, Permissions & Users
Route::resource('/roles', 'API\RoleController');
Route::resource('/permissions', 'API\PermissionController');
Route::resource('/users', 'API\UserController');

//Auditoria
Route::resource('/auditorias', 'AuditController');

src/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Code Provider">
    <meta name="author" content="Code And Coffee - www.codeandcoffee.com.br">
    <meta name="keyword" content="Code and coffee,Code Provider">
    <link rel="shortcut icon" href="favicon.ico">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.title', 'PMA - 2020') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<!--
    {{--  BODY options, add following classes to body to change options

// Header options
1. '.header-fixed'                  - Fixed Header

// Brand options
1. '.brand-minimized'       - Minimized brand (Only symbol)

// Sidebar options
1. '.sidebar-fixed'                 - Fixed Sidebar
2. '.sidebar-hidden'                - Hidden Sidebar
3. '.sidebar-off-canvas'        - Off Canvas Sidebar
4. '.sidebar-minimized'         - Minimized Sidebar (Only icons)
5. '.sidebar-compact'             - Compact Sidebar

// Aside options
1. '.aside-menu-fixed'          - Fixed Aside Menu
2. '.aside-menu-hidden'         - Hidden Aside Menu
3. '.aside-menu-off-canvas' - Off Canvas Aside Menu

// Breadcrumb options
1. '.breadcrumb-fixed'          - Fixed Breadcrumb

// Footer options
1. '.footer-fixed'                  - Fixed footer  --}}

-->

<body class="app sidebar-lg-show sidebar-fixed header-fixed aside-menu-fixed aside-menu-hidden ">
    @include('layouts.header')
    <div class="app-body">
        @include('layouts.sidebar')
        <!-- Main content -->
        <main class="main">
            <div class="container-fluid">
                <div class="animated fadeIn">
                    @yield('content')
                </div>
            </div>
            <!-- /.conainer-fluid -->
        </main>
    </div>
    @include('layouts.footer')
    <!-- Scripts -->
    <script type="text/javascript">
        var APP_URL = {!! json_encode(url('/')) !!}
    </script>
    <script src="{{ asset('js/pace.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>

</body>


</html>

src/resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app" class="app flex-row align-items-center">
        <div class="container">
            <div class="row justify-content-center">
                @yield('auth')
            </div>
        </div>
    </div>
</body>
</html>

src/resources/views/layouts/footer.blade.php
<footer class="app-footer">
    <span>v1.0.0-Alpha</span>
    <span class="ml-auto">Powered by <a href="http://gitlab.com/ozodrac">Code And Coffee</a></span>
</footer>

src/resources/views/layouts/header.blade.php
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url('/') }}">
        {{-- <img class="navbar-brand-full" src="svg/modulr.svg" width="89" height="25" alt="Modulr Logo">
        <img class="navbar-brand-minimized" src="svg/modulr-icon.svg" width="30" height="30" alt="Modulr Logo"> --}}
    </a>
    {{-- <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button> --}}
    <ul class="nav navbar-nav ml-auto mr-3">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                @if (Auth::user()->avatar_url)
                    <img class="img-avatar mx-1" src="{{Auth::user()->avatar_url}}">
                @else
                    {{-- <img class="img-avatar mx-1" src="/images/avatars/6.jpg"> --}}
                    <i class="fa fa-lg fa-user-circle"></i>
                @endif
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow mt-2">
                <div class="dropdown-header text-center"><strong>Account</strong></div>
                <a class="dropdown-item">
                    {{ Auth::user()->name }}<br>
                    <small class="text-muted">{{ Auth::user()->email }}</small>
                </a>
                <a class="dropdown-item" href="{{route('profile')}}"><i class="fas fa-user"></i> Profile</a>
                <div class="divider"></div>

                <a class="dropdown-item" href="{{route('password')}}"><i class="fas fa-key"></i> Password</a>
                <div class="divider"></div>

                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</header>

src/resources/views/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link active" href="/">
                    <i class="nav-icon icon-speedometer"></i> Inicio
                </a>
            </li>
            {{-- <li class="nav-title "> Configurações</li> --}}
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-shield-alt"></i> Segurança</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('auditorias.index') }}"><i class="fas fa-book"></i>
                            Auditorias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('permissions.index') }}"><i class="icon-lock-open"></i>
                            Permissões</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('roles.index') }}"><i class="fa fa-user-shield"></i>
                            Perfil de Usuário</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('users.index')}}"><i class="fa fa-users"></i> Usuários</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('secretarias.index')}}">
                    <i class="fa fa-university"></i> Secretarias
                </a>
            </li>

            @if(auth()->user()->hasRole('Admin'))
            {{-- <li class="nav-item">
                    <a class="nav-link" href="{{route('endpoints.index')}}">
            <i class="icon-link"></i> Endpoints
            </a>
            </li> --}}
            @endif
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>